# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='indica el nombre de la sala', max_length=30, verbose_name='Nombre')),
                ('ubicacion', models.TextField(help_text='indica la ubicacion de la sala', max_length=30, verbose_name='Ubicacion')),
                ('capacidad', models.IntegerField(help_text='indica  la capacidad en numero de personas de la sala', verbose_name='Capacidad')),
                ('horario_disponibilidad', models.TimeField(help_text='indica la hora disponible', verbose_name='Horario de Disponibilidad')),
            ],
        ),
    ]
